### ISSUE TITLE
How to download it

### ISSUE THREAD

**Issue by Goldenhawkplayz** [CDAGaming/CrystalOptimizer#8]
i go in 1.16.5 but i cant download its jar file

**Comment by Skygamer10** [comment]
You need to join Marlow's official discord server --> .gg/marlow --> in #mods

**Comment by Skygamer10** [comment]
Oh and it isn't available in 1.16, only 1.18.2 and 1.19

**Comment by CDAGaming** [comment]
#1

**Comment by CoronaryConch** [comment]
> #1
how to download the jar file. The zip file is not shown in the mods.
